### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [mmazzarolo/easy-bookmarks#1]
Hi do you have a version of this app with out all these third part libs listed below?

Butterknife
Recyclerview-animators
Picasso
Logger
Recyclerview-animators
FlowLayout
TokenAutoComplete
Vector Compat
Clans FAB
MaterialShowcaseView

**Comment by mmazzarolo** [comment]
Hi,
no, I'm sorry, many of the third part libraries I used are needed for the app.
May I ask you the reason of this request?

**Comment by ghost** [comment]
I'm looking a for clean bookmark manager using no 3rd party libraries. just looking for it for personal use. Just using standard android features.

**Comment by mmazzarolo** [comment]
Oh, I'm sorry man, you should search for something else then :-1:

**Comment by ghost** [comment]
All good thanks man nice app by the way

**Comment by ghost** [comment]
@mmazzarolo Would it be okay with you if i try make it with out using any third party apps using some your code?

If i may must i provide any license

**Comment by mmazzarolo** [comment]
Of course, no license needed: Just fork it and have fun!

Keep in mind that you must provide a valid Firebase URL (register a new free account on [Firebase.com](https://www.firebase.com/) and change the `firebase_url` string in [res/values/strings.xml](https://github.com/mmazzarolo/easy-bookmarks/blob/master/app/src/main/res/values/strings.xml))

If you need any further information please do not hesitate to contact me ;)
