### ISSUE TITLE
Invalid Firebase URL

### ISSUE THREAD

**Issue by bkitduy** [mmazzarolo/easy-bookmarks#2]
And here is my error on logcat: EasyBookmarksApplication: com.firebase.client.FirebaseException: Invalid Firebase url specified. 
Would you like to provide me a valid Firebase URL to test your library

**Comment by mmazzarolo** [comment]
Hello!
Unfortunately I can't provide you a Firebase URL but you can easily get one by yourself with a free Firebase account.
Just register a new free account on [Firebase.com](https://www.firebase.com/) and change the `firebase_url` string in [res/values/strings.xml](https://github.com/mmazzarolo/easy-bookmarks/blob/master/app/src/main/res/values/strings.xml).
Hope I helped :)

**Comment by bkitduy** [comment]
Thanks so much

**Comment by abuhenasobuj** [comment]
- Google Sign-up for user identification 
- Firebase for storing and sync data and managing user authorizations

How does google sign-up function work?
How do add (Setup) Firebase URL?
